[package]
name = "vrc_yt-dlp_workaround"
version = "0.3.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.101"
dialoguer = "0.12.0"
reqwest = { version = "0.13.2", features = ["blocking"] }
tempfile = "3.25.0"
zip = "8.0.0"
